spring:
    application:
        name: task-manager
    datasource:
        driver-class-name: org.h2.Driver
        password: password
        river-class-name: org.h2.Driver
        url: jdbc:h2:mem:test;
        username: sa
    h2:
        console:
            enabled: true