spring:
    application:
        name: task-manager
    datasource:
        driver-class-name: org.h2.Driver
        password: password
        river-class-name: org.h2.Driver
        url: jdbc:h2:mem:test;
        username: sa
    h2:
        console:
            enabled: true

    mail:
        host: smtp.example.com
        port: 587
        username: your_email@example.com
        password: your_password
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
